Task 1:
1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [6]:
def division():
    try:
        print (5/0)
    except:
        print("Divisor could not be equal to zero")

In [7]:
division()

Divisor could not be equal to zero


Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [9]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence_list = [(sub+' '+vb+' '+obj) for sub in subjects for vb in verbs for obj in objects ]
for sentence in sentence_list:
    print(sentence)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [4]:
import numpy as np
x = np.array([1,2,3,4])
N = 4
matrix = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [5]:
import numpy as np
x = np.array([1,2,3,4])
N = 4
matrix1 = np.vander(x,N,increasing=True)

print(matrix1)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
